### ISSUE TITLE
rdfs:name not systematic for labelling

### ISSUE THREAD

**Issue by lvaudor** [lvaudor/glitter#168]
Hi,
Just found a triplestore where labelling with rdfs:name does not work. HAL seems to use "skos:prefLabel" instead.
Maybe we should take this into account in our spq_label() function ?

**Comment by lvaudor** [comment]
Maybe we could have an argument prop="rdfs:name" by default in spq_label hence we could put spq_label(prop="skos:prefLabel") for hal?

**Comment by maelle** [comment]
how about it's something done at the spq_init() stage, initializing an endpoint with more details (URL, name of label property).

For HAL we'd store the info in our internal data as an usual endpoint.

We'd remove the endpoint argument from spq_perform() because that'd be something defined in .query thanks to spq_init().

**Comment by lvaudor** [comment]
Yes, sounds perfect!

**Comment by maelle** [comment]
@lvaudor any query example?
