### ISSUE TITLE
Fix transform_wikidata_coords example

### ISSUE THREAD

**Issue by maelle** [lvaudor/glitter#179]
@lvaudor do you remember what the query string meant? It doesn't yield any result now.

**Comment by lvaudor** [comment]
I think it came from the glitter + Wikidata vignette (this is a query about Lyon Metro Network stations, the property has changed since then).
Anyway, we can remove this function from the package... It's too Wikidata-centered, and I think it's not useful anymore (now that I discovered that this "WKT" format integrates well with sf for instance). See new Wikidata article where I use these coordinates in tibble_as_sf() or something like that.
